server:
  port: 9098
spring:
  application:
    name:  ProductService
  datasource:
    url: jdbc:mysql://localhost:3306/ust
    username:  root
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true